# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: templates_template2
on:
  workflow_call:
    inputs:
      TargetBranch:
        required: false
        default: "$(Build.SourceBranch)"
        type: string
jobs:
  template2:
    name: run template2 tasks
    runs-on: windows-latest
    timeout-minutes: 180
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - uses: actions/checkout@v3.3.0
    - name: Generate NuGet.config to Temp directory
      if: 'false'
      shell: pwsh
      run: |-
        $params = ""C:\Program Files\org\tool\nuget.exe" "${{ runner.temp }}\NuGet.config" ${{ env.artifactoryuser }} ${{ env.agentpassword }}"
        $scriptBlock = @'
        param(
         $nugetExecutablePath,
         $configPath,
         $artifactoryuser,
         $artifactorypassword
        )
        @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration/>
        "@ | Set-Content $configPath
        & "$nugetExecutablePath" sources add -Name "OrgNugets" -Source "https://artifactory.organization.com:443/artifactory/OrgNugets/" -Config $configPath -username "$artifactoryuser" -password "$artifactorypassword"
        '@
        $func = New-Item -Path function: -Name inline_script_$(Get-Random) -Value $scriptBlock
        Invoke-Expression "$func $params"
  templates_more_template3-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: Test myAction
      run: |-
        pwsh -File myAction.ps1
             -SourceRootDirectory ${{ github.workspace }}
             -FolderToCheckIn ${{ github.workspace }}\demo-app\
             -FileExtensionsToCheckIn *.md
             -CheckInComment generatedmdfiles
             -MakeCheckIn false
             -SourceBranch ${{ github.ref }}
      shell: pwsh
