name: templates_more_template3
runs:
  using: composite
  steps:
#   # This item has no matching transformer
#   - task: myAction@6
#     displayName: Test myAction
#     inputs:
#       FolderToCheckIn: "${{ github.workspace }}\\demo-app\\"
#       SourceRootDirectory: "${{ github.workspace }}"
#       FileExtensionsToCheckIn: "*.md"
#       CheckInComment: generatedmdfiles
#       MakeCheckIn: 'false'
#       SourceBranch: "${{ github.ref }}"