---
trigger:
- none
pool:
  vmImage: windows-latest
variables:
  solution: "**/*.sln"
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
- job: Build
  steps:
  - task: VisualStudioTestPlatformInstaller@1
    displayName: Visual Studio Test Platform Installer
    inputs:
      versionSelector: specificVersion
      testPlatformVersion: 17.5.0
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"
  - task: VSBuild@1
    inputs:
      solution: "$(solution)"
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true
        /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"
        /p:DeployIisAppPath="Default Web Site"
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"
  - task: VSTest@2
    inputs:
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"
  - template: templates/template1.yml
  - template: templates/template2.yml
    parameters:
      TargetBranch: main
